### ISSUE TITLE
Custom payment method in PWA

### ISSUE THREAD

**Issue by phuhung273** [larsroettig/larsroettig-next#30]
### Issue
Thank you for your blog. I'm following this article https://larsroettig.dev/demystified-pwa-studio-checkout but the custom payment method is not showing.

### What I've tried
src/components/solpay.js
```
const Solpay = props => {
    const {
        classes: propClasses,
    } = props;

    return (
        <div className={classes.root} data-cy="Solpay-root">
            Hello Solpay
        </div>
    );
};

export default Solpay;
```

intercept.js
```
/** Registers our Payment **/
const { checkoutPagePaymentTypes } = targets.of("@magento/venia-ui");
checkoutPagePaymentTypes.tap((payments) =>
    payments.add({
        paymentCode: "solpay",
        importPath: "@phuhung273/solpay/src/components/solpay.js"
    })
);
```

package.json
```
"peerDependencies": {
  "@magento/pwa-buildpack": ">=6.0.0",
  "@magento/venia-ui": "*",
},
"dependencies": {
  "@phuhung273/solpay": "link:./@phuhung273/solpay"
},
```

### Possible solution
In your post, there's a part:

> Loads all available Payments via usePaymentMethods hook and compares them with paymentMethodCollection.js, built via Magento Target.
> **It only renders components that both lists contain!**

Is this because the payment method is not enabled on the backend ?

Thank you for your help

**Comment by larsroettig** [comment]
@phuhung273 I don't maintained this blog longer !
